version: "3"
services:
  db:
    image: 'postgres:14-alpine'
    environment:
      POSTGRES_DB: demo_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  pgdata: